### ISSUE TITLE
Not working anymore? / Can't get posts

### ISSUE THREAD

**Issue by ItsEcholot** [replay42/JodelPHP#1]
Hey, I don't know if the api is outdated but I can't get posts using the provided samples or code made by me.

**Comment by replay42** [comment]
I'm sorry, I know it's not working anymore.
The API was rebuilt. Maybe I'm going to rebuild this project as well.

**Comment by ItsEcholot** [comment]
That would be awesome, hit me up if I can help you somehow

**Comment by shock2provide** [comment]
Maybe we should also move this project into a private repository (for obvious reasons) and provide the source per invites or something like that.

**Comment by ghost** [comment]
Are there any news? I would like to use this API :)

**Comment by LauertBernd** [comment]
Hey, i created a similar project, and hope that i will make it work somehow. please have a look:
https://github.com/LauertBernd/JodelClientPHP

**Comment by datagutten** [comment]
Working again after #2
